### ISSUE TITLE
In XPATH I use '''...and''' to add an additional criterion, in cheeriogs is there this option?

### ISSUE THREAD

**Issue by fredericomattos** [tani/cheeriogs#138]
**_First I would like to thank for the project because it is magnificent, second I want to apologize for the beginner question and I hope don't think it's bad for me to ask for help in the doubt._**

Using `=IMPORTXML('url','xpath')` I make the call with this XPATH:

`//div[contains(@class,'match-card') and ../../td[@class='score-time ']/a[contains(@href, 'matches')]]`

The idea is to collect the `div` that contain the `@class` with the word `match-card`
BUT 
he needs to have `td` linked to `@class='score-time'` and `a` contains the `@href` with the word `matches`

I tried to find a way to do this with CHEERIOGS but it always returns blank, my attempts were:

```
    $('tr:contains(td.score-time > a[href^="/matches/"]) > div[class^="match-card"]')
                  .each((index, element) => {ss.getRange(index + 2, 2).setValue($(element).text().trim());});
```

```
    $('tr td.score-time:contains(a[href^="/matches/"]) > div[class^="match-card"]')
                  .each((index, element) => {ss.getRange(index + Alast + 2, 2).setValue($(element).text().trim());});
```
```
    $('tr td.score-time > a[href^="/matches/"] > div[class^="match-card"]')
                  .each((index, element) => {ss.getRange(index + Alast + 2, 2).setValue($(element).text().trim());});
```

Could help me on how I could go about achieving my expected result?

**Comment by tani** [comment]
First, thank you for using my library. The expressive power of xpath is stronger than css selector. Generally speaking, we cannot translate xpath to css selector on the straight forward. However, I guess the following code may work as you expect. Please try this.

```
td.score-time a[href*="matches"] div.match-card
```

This question is not directly related to this library. I mean, you can get the better answer on the Stackoverflow because this is the problem how to translate xpath to css selector. Of course, I have a little bit tips about this. Please attach (i) target xml data (ii) xpath code (iii) expected **raw** result if you want to ask me more detail.

**Comment by fredericomattos** [comment]
Hi @tani as I didn't know about the availability to solve doubts around here, I created a question on Stackoverflow, if you want and can analyze if there is anything to add and complement, here is the link:

https://stackoverflow.com/questions/71346261/in-xpath-i-use-and-to-add-an-additional-criterion-in-cheerio-is-there

**Comment by tani** [comment]
I am really happy you finally get the answer. Congrats!
