### ISSUE TITLE
Limit on query?

### ISSUE THREAD

**Issue by JoseLuisPozo** [tani/cheeriogs#182]
Hi all!
Are there any limits with CSS selectors?
It only returns the first 50 elements

`let items = $('.grid__Name-cmp__sc-li856a-4');`

Thanks and best regards

**Comment by tani** [comment]
HI. Thank you for using my library.
I surely say that there is no limitation to the number of elements to
retrieve.
It might be caused by the limitation as follows.

- They fetch the website by an HTTP request.
- As the initial response, the server returns only 50 elements.
- After the loading pages, the website newly fetches other elements by
JavaScript.

Unfortunately, cheerio is not a browser. That's why cheerio does not
interpret JavaScript written in websites.
Thus, you could retrieve only 50 elements as an initial response.

2022年11月18日(金) 19:08 Jose Luis Pozo ***@***.***>:

**Comment by JoseLuisPozo** [comment]
Thank you so much!
